# Generated by Django 4.0.4 on 2022-05-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtmodel',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
