# Generated by Django 4.0.4 on 2022-06-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_debtmodel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmodel',
            name='status',
            field=models.CharField(choices=[('C', 'choosing'), ('S', 'started'), ('R', 'returned'), ('T', 'to_be_returned')], max_length=1),
        ),
    ]
