# Generated by Django 4.0.4 on 2022-06-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_bookmodel_author_alter_bookmodel_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
