# Generated by Django 4.0.4 on 2022-05-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=12)),
                ('gender', models.CharField(choices=[('F', 'female'), ('M', 'male')], max_length=1)),
                ('address', models.TextField()),
                ('national_code', models.CharField(max_length=10)),
            ],
        ),
    ]
